"""Add users and API key tables

Revision ID: 5e3620932770
Revises: 
Create Date: 2025-10-26 16:02:27.902944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3620932770'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futures_coinm_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('pair', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('leverage', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_futures_coinm_trades_id'), 'futures_coinm_trades', ['id'], unique=False)
    op.create_index(op.f('ix_futures_coinm_trades_pair'), 'futures_coinm_trades', ['pair'], unique=False)
    op.create_index(op.f('ix_futures_coinm_trades_username'), 'futures_coinm_trades', ['username'], unique=False)
    op.create_table('futures_usdm_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('pair', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('leverage', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_futures_usdm_trades_id'), 'futures_usdm_trades', ['id'], unique=False)
    op.create_index(op.f('ix_futures_usdm_trades_pair'), 'futures_usdm_trades', ['pair'], unique=False)
    op.create_index(op.f('ix_futures_usdm_trades_username'), 'futures_usdm_trades', ['username'], unique=False)
    op.create_table('margin_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('pair', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('leverage', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_margin_trades_id'), 'margin_trades', ['id'], unique=False)
    op.create_index(op.f('ix_margin_trades_pair'), 'margin_trades', ['pair'], unique=False)
    op.create_index(op.f('ix_margin_trades_username'), 'margin_trades', ['username'], unique=False)
    op.create_table('options_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('pair', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('option_type', sa.String(), nullable=True),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_trades_id'), 'options_trades', ['id'], unique=False)
    op.create_index(op.f('ix_options_trades_pair'), 'options_trades', ['pair'], unique=False)
    op.create_index(op.f('ix_options_trades_username'), 'options_trades', ['username'], unique=False)
    op.create_table('p2p_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p2p_orders_id'), 'p2p_orders', ['id'], unique=False)
    op.create_table('spot_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('pair', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_trades_id'), 'spot_trades', ['id'], unique=False)
    op.create_index(op.f('ix_spot_trades_pair'), 'spot_trades', ['pair'], unique=False)
    op.create_index(op.f('ix_spot_trades_username'), 'spot_trades', ['username'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('balance_inr', sa.Float(), nullable=True),
    sa.Column('balance_usdt', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_spot_trades_username'), table_name='spot_trades')
    op.drop_index(op.f('ix_spot_trades_pair'), table_name='spot_trades')
    op.drop_index(op.f('ix_spot_trades_id'), table_name='spot_trades')
    op.drop_table('spot_trades')
    op.drop_index(op.f('ix_p2p_orders_id'), table_name='p2p_orders')
    op.drop_table('p2p_orders')
    op.drop_index(op.f('ix_options_trades_username'), table_name='options_trades')
    op.drop_index(op.f('ix_options_trades_pair'), table_name='options_trades')
    op.drop_index(op.f('ix_options_trades_id'), table_name='options_trades')
    op.drop_table('options_trades')
    op.drop_index(op.f('ix_margin_trades_username'), table_name='margin_trades')
    op.drop_index(op.f('ix_margin_trades_pair'), table_name='margin_trades')
    op.drop_index(op.f('ix_margin_trades_id'), table_name='margin_trades')
    op.drop_table('margin_trades')
    op.drop_index(op.f('ix_futures_usdm_trades_username'), table_name='futures_usdm_trades')
    op.drop_index(op.f('ix_futures_usdm_trades_pair'), table_name='futures_usdm_trades')
    op.drop_index(op.f('ix_futures_usdm_trades_id'), table_name='futures_usdm_trades')
    op.drop_table('futures_usdm_trades')
    op.drop_index(op.f('ix_futures_coinm_trades_username'), table_name='futures_coinm_trades')
    op.drop_index(op.f('ix_futures_coinm_trades_pair'), table_name='futures_coinm_trades')
    op.drop_index(op.f('ix_futures_coinm_trades_id'), table_name='futures_coinm_trades')
    op.drop_table('futures_coinm_trades')
    # ### end Alembic commands ###
